### ISSUE TITLE
chaotic aur Synchronizing package databases repeatedly

### ISSUE THREAD

**Issue by QiangF** [chaotic-aur/toolbox#30]
Sometimes I need to run pacman -Syu several times to get all update, because of slow internet connection.

For other repos， if I ran “pacman -Syu”several times consecutively. The data base is only need to down load once. Subsequent invocation will show something like:

     core is up to date
     extra is up to date
     community is up to date

But this is not the case for chaotic, it need to update the database each time. There must be something wrong.

**Comment by PedroHLC** [comment]
Check if new packages were added between the time you ran the commands: https://t.me/chaotic_aur_deploy_log

If they were not, then please provide us the first `Server =` you have in your `/etc/pacman.d/chaotic-mirrorlist`

**Comment by QiangF** [comment]
In my /etc/pacman.conf

    [chaotic-aur]
    Server = https://kr-mirror.chaotic.cx/$repo/$arch

And this is the terminal output just now. I don't think there are any new packages added during this short period.

    q@mypc:.dotfiles$ pacu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
     archlinuxcn is up to date
     arch4edu is up to date
     chaotic-aur                                                                          1611.3 KiB  28.9 KiB/s 00:56     [#####################################################################] 100%
    :: Starting full system upgrade...
     there is nothing to do
    q@mypc:.dotfiles$ date
    2022年 03月 17日 星期四 21:10:15 CST
    q@mypc:.dotfiles$ pacu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
     archlinuxcn is up to date
     arch4edu is up to date
     chaotic-aur                                                                          1611.3 KiB  57.8 KiB/s 00:28 [#####################################################################] 100%
    :: Starting full system upgrade...
     there is nothing to do
    q@mypc:.dotfiles$ date
    2022年 03月 17日 星期四 21:10:48 CST
    q@mypc:.dotfiles$ pacman -Syu
    error: you cannot perform this operation unless you are root.
    q@mypc:.dotfiles$ sudo pacman -Syu
    :: Synchronizing package databases...
     core is up to date
     extra is up to date
     community is up to date
     multilib is up to date
     archlinuxcn is up to date
     arch4edu is up to date
     chaotic-aur                                                                          1611.3 KiB  59.9 KiB/s 00:27 [#####################################################################] 100%
    :: Starting full system upgrade...

**Comment by silent-heigou** [comment]
Thank you for reporting the problem. My web server was not handling headers of files properly including the database file of the repository. It will not be downloaded over and over now.

**Comment by PedroHLC** [comment]
@QiangF can you check if it was solved?

Thanks @silent-heigou

**Comment by QiangF** [comment]
Problem solved. Thank you!
