### ISSUE TITLE
Delta update support (pacman)

### ISSUE THREAD

**Issue by RubenKelevra** [chaotic-aur/toolbox#40]
Hey guys,

I did some testing on how efficient delta updates (if implement) would be in pacman. And since you're having one of the biggest packages around, I thought you might be interesting to take a look at the findings and take part in the discussion:

https://lists.archlinux.org/pipermail/pacman-dev/2022-May/025568.html

The numbers are super promising, with an average saving of 40% on "source code heavy" packages and sometimes above 99% for data heavy packages with applying times below 1 second on modern computers.

Best regards,

Ruben

**Comment by Technetium1** [comment]
Interesting concept, but not sure that it'll be implemented or until it's more widely used. The more I read about it the more it seems that was killed off because no official repos used it. Thanks for posting, looking forward to reading others' views.
https://www.reddit.com/r/archlinux/comments/b7zkg5/why_delta_support_removed_from_pacman/

**Comment by PedroHLC** [comment]
We have packages like `mesa-*-git` that update every hour, others that don't do so much, but their diff is quite big.
If we save like "a month-old" of delta packages, we would need at least four times the amount of space we're using now. For our main node that wouldn't be a problem but most of our mirrors are very low-tier VPS running on small SSDs.

**Comment by RubenKelevra** [comment]
@PedroHLC wrote:
> We have packages like `mesa-*-git` that update every hour, others that don't do so much, but their diff is quite big.

I've tested this:

`mesa-tkg-git-22.2.0_devel.153443.a7f44b62694-1-x86_64.pkg.tar` to `mesa-tkg-git-22.2.0_devel.153445.d2ab0ed31e1-1-x86_64.pkg.tar` would be 3.8M and  `mesa-tkg-git-22.2.0_devel.153445.d2ab0ed31e1-1-x86_64.pkg.tar` to `mesa-tkg-git-22.2.0_devel.153609.2b28668d1da-1-x86_64.pkg.tar` would be 22M.

So that's a saving of 92.8% and 58.5%.

And yes, that's maybe not something every mirror wants to store. But on the other hand, that's fully optional – you can just create two tiers.

I'm for example happy to store 2-3 days worth of deltas on my mirrors, if this allows users to install updates more often or faster.

**Comment by PedroHLC** [comment]
I doubt this is is anyone's priority list to implement, so let me close this. In case someone is interested feel free to open a PR.

**Comment by VexfulNiko** [comment]
No idea how to do this but I would be interested into this being implemented
