### ISSUE TITLE
[Discussion] Base Singularity on base-devel instead of base-master

### ISSUE THREAD

**Issue by Gontier-Julien** [chaotic-aur/toolbox#59]
I propose some change on the `Singularity` file for the toolbox, i don't know why it was setup that way (and i think there was a very good reason behind it, so clear me up if i'm wrong).
But since it in a clean docker anyway, there shouldn't be any issues to go directly grab the base-devel docker container. And with that we could remove the pacman line to go grab it.

`From: gitlab.archlinux.org:5050/archlinux/archlinux-docker:base-master`
`pacman -Syyu --noconfirm --noprogressbar --quiet`
`pacman -S --noconfirm --noprogressbar --quiet base base-devel`

to

`From: gitlab.archlinux.org:5050/archlinux/archlinux-docker:base-devel`
 `pacman -Syyu --noconfirm --noprogressbar --quiet`

**Comment by PedroHLC** [comment]
> i don't know why it was setup that way (and i think there was a very good reason behind it, so clear me up if i'm wrong).

Actually, neither me nor @thotypous was aware of the existence of the base-devel image when we ported it to singularity.

Feel free to open a PR to keep your credits.

**Comment by Gontier-Julien** [comment]
> > i don't know why it was setup that way (and i think there was a very good reason behind it, so clear me up if i'm wrong).
> 
> Actually, neither @thotypous nor I was aware of the existence of the base-devel image when we ported it to singularity.
> 
> Feel free to open a PR to keep your credits.

Alright doing that right now!
