### ISSUE TITLE
Use PNPM instead of Yarn

### ISSUE THREAD

**Issue by VexfulNiko** [chaotic-aur/toolbox#65]
PNPM is faster than yarn and has a lot more customizability than yarn. Would be an excellent choice to speedup the toolchain.

**Comment by JustTNE** [comment]
I'm not sure what this issue is about? The toolbox does not make use of yarn or any JS dependencies at runtime, only for shellcheck. We are definitely 100% not changing packages to use pnpm instead, that is the AUR maintainers decision.
