### ISSUE TITLE
 Import PGP key 349BC7808577C592? [Y/n] error: required key missing from keyrin"

### ISSUE THREAD

**Issue by bf** [chaotic-aur/toolbox#86]
I get error message `Import PGP key 349BC7808577C592? [Y/n] error: required key missing from keyrin` even though website says `pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com`.

The keys differ. I tried different mirrors.

**Comment by dr460nf1r3** [comment]
Yeah, I updated the mirrorlist yesterday and forgot it needs to be built by the ufscar node these days (it didn't need to be the time before). 
Bumped it here, so it should be available in a few hours: https://github.com/chaotic-aur/pkgbuild-chaotic-mirrorlist/commit/56423742f42ff4be23bce65f0bfb95c9bf788da3

**Comment by bf** [comment]
Thanks  @dr460nf1r3 - I discussed this on #archlinux a bit. What solved the issue for me is to run pacman -U chaotic-keyring and then pacman -U chaotic-mirrorlist. So maybe if the website is adapted to split the pacman -U to two calls instead of one it'd also work.
