### ISSUE TITLE
[Request] universal interfere

### ISSUE THREAD

**Issue by xiota** [chaotic-aur/toolbox#89]
Add an interfere that applies to *all* packages.

Can be used to do some clean-up that should be applied to all packages, like:

* Remove `groups`.
* Remove `replaces`.
* Add new-line to the end of `PKGBUILD` to prevent problems like [this](https://builds.garudalinux.org/repos/chaotic-aur/logs/avaloniailspy.log).

**Comment by PedroHLC** [comment]
https://github.com/chaotic-aur/toolbox/blob/90c3586d7c683fb705796a97ca2ecdc65fa90420/src/lib/interfere.sh#L39

This is what this function is all about.

**Comment by Technetium1** [comment]
Double check me, but this could do last point
```
# * Add newline to end if there is not
if [[ $(tail -c 1 "PKGBUILD" | wc -l) -eq 0 ]]; then
    echo -e "\n" >> "PKGBUILD"
fi
```

**Comment by xiota** [comment]
@Technetium1 Why not just unconditionally `printf "\n" >> PKGBUILD` ?

**Comment by Technetium1** [comment]
@xiota yes lol, that's valid and much simpler. I was assuming it would be less intensive to not write to _all_ the files, instead only appending if needed. If it's running in memory (which I think it might be right now actually), then it's probably faster to just append the newline blindly.

**Comment by xiota** [comment]
What about storing everything that needs to be appended in a variable.
```
_PKGBUILD_APPEND+=$'unset PKGEXT\n'
_PKGBUILD_APPEND+=$'unset groups\n'
_PKGBUILD_APPEND+=$'unset replaces\n'

printf '\n\n%s\n' "$_PKGBUILD_APPEND" >> PKGBUILD
```

**Comment by dr460nf1r3** [comment]
TIL! Didn't know this was possible, sounds very handy!

**Comment by PedroHLC** [comment]
> What about storing everything that needs to be appended in a variable.

We can already append to the PKGBUILD at any time. This is not better than what we already have.

> Would also be nice for packages with pkgver() to set pkgver, pkgrel, epoch to match last built package. That should allow bumps to work for -git packages.

This sounds more as an adjusts that should be done in the bump interference (by detecting functions and treating them). But remember, we can't really call pkgver ahead-of-time since they execute code that needs to be run inside the building container.

For this last one open a new issue, it's quite unrelated to this.
